server:
    port: 8082
    
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_NAME}:${DB_PWD}@${CLUSTER_URI}/${DB_NAME}?retryWrites=true&w=majority
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    requested-heartbeat: 580
    cache:
      channel:
        size: 25
    virtual-host: eldycare_broker
  main:
    allow-bean-definition-overriding: true
    
notification:
  rabbitmq:
    notificationQueue: notificationQueue
    relativeQueue: relativeQueue
    exchange: amq.topic
    notificationRoutingkey: 'notificationkey.#.*'
    relativeRoutingKey: 'relativeKey.#.*'
